import { Testcase } from './testcase';
export const MockedTestcases: Testcase[] = [
  {
    '_id': '94994594',
    'key': 'TC01',
    'testSuiteId': '45069c63096d72f89cbf9205d27c985b',
    'priority': 1,
    'order': 2,
    'preConditions': 'Preconditions 1',
    'title': 'Testcase 1',
    'description': 'Test case description',
    'steps': ['Check that', 'Check this'],
    'testData': ['data1', 'data2'],
    'expected': ['Expected that', 'Expected this'],
    'postConditions': 'Postconditions 1',
    'tags': ['first tag', 'second tag'],
    'estimate': 10,
    'enabled': true,
    'isAutomated': false,
    'status': 'created',
    'created': '',
    'updated': '',
    'createdBy': '',
    'updatedBy': ''
  },
  {
    '_id': '92e2e2e4994594',
    'key': 'TC02',
    'testSuiteId': '11111c63096d72f89cbf9205d27c985b',
    'priority': 1,
    'order': 2,
    'preConditions': 'Preconditions 2',
    'title': 'Testcase 2',
    'description': 'Test case description',
    'steps': ['Check that', 'Check this'],
    'testData': ['data1', 'data2'],
    'expected': ['Expected that', 'Expected this'],
    'postConditions': 'Postconditions 2',
    'tags': ['first tag', 'second tag'],
    'estimate': 10,
    'enabled': true,
    'isAutomated': false,
    'status': 'created',
    'created': '',
    'updated': '',
    'createdBy': '',
    'updatedBy': ''
  }
];
