name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Run Frontend tests
      run: npm run test

  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        cd server
        npm install
    - name: Run Backend tests
      run: |
        export SECRET=mytestsecret
        cd server
        npm run test

  deploy-frontend-heroku:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: test-storage
      run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

  deploy-backend-heroku:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: test-storage-api
      run: |
          cd ./server
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
